audit_header: false
title: Charleston Real Estate Video Blog with Michael Smith
description: Our mission at Top Charleston Agents Real Estate Team is to be your best resource for Charleston real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Top Charleston Agents Real Estate Team, your professional Charleston Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Michael Smith
  title:
  license_number:
  about_markdown: |
    Our Team specializes in all things Charleston Real Estate... Both Commercial and Residential! Welcome to the Low Country of Charleston, South Carolina. With Berkshire Hathaway HomeServices Carolina Sun Real Estate and the Leader of the Top Charleston Agents Team, we are experts in all things Real Estate anywhere in the Charleston area.

    We serve the areas of Mt Pleasant, Daniel Island, Wando,James Island, Johns Island, West Ashley, Hollywood, Ravenel, and the Beach communities of Isle of Palms,Sullivan’s Island, Seabook Island, Kiawah Island, Folly Beach, Wadmala Island, Edisto Island. We also sell real estate in the Summerville, Hanahan, Goose Creek, Ladson, N Charleston, and Moncks Corner areas.
  brand: Top Charleston Agents Real Estate Team
  brokerage: Berkshire Hathaway HomeServices
  market: Charleston
  address:
  phone: 843-580-6251
  phone_type:
  phone2:
  phone2_type:
  email: agents@topcharlestonagent.com
  url: http://TopCharlestonAgents.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.topcharlestonagents.com/sell.php
  second_CTA_text: Home Search
  second_CTA_URL: https://www.topcharlestonagents.com/index.php?advanced=1&display=Charleston,%20Dorchester,%20Colleton,%20Berkeley&areas[]=county:Charleston&areas[]=county:Dorchester&areas[]=county:Colleton&areas[]=county:Berkeley&beds=0&baths=0&min=0&max=100000000&minacres=0&maxacres=3000&minfootage=0&maxfootage=30000&walkscore=&yearbuilt=0&options[]=new&sortby=listings.listingdate%20DESC&ppc=Paid%20Marketing%20(PPC)&agency_photos=&view_timing=2#rslt

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Charleston Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.topcharlestonagents.com/sell.php

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Charleston Home?"
    CTA_text2: "Search the entire MLS for your Charleston home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.topcharlestonagents.com/index.php?advanced=1&display=Charleston,%20Dorchester,%20Colleton,%20Berkeley&areas[]=county:Charleston&areas[]=county:Dorchester&areas[]=county:Colleton&areas[]=county:Berkeley&beds=0&baths=0&min=0&max=100000000&minacres=0&maxacres=3000&minfootage=0&maxfootage=30000&walkscore=&yearbuilt=0&options[]=new&sortby=listings.listingdate%20DESC&ppc=Paid%20Marketing%20(PPC)&agency_photos=&view_timing=2#rslt

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://business.facebook.com/TopCharlestonAgents/?business_id=10153283000255325
  linkedin_url: https://www.google.com/url?q=https://www.linkedin.com/company/topcharlestonagents&sa=D&source=hangouts&ust=1588087002905000&usg=AFQjCNHAyqBF0l72UgSok-Ur9KpNvPsFUQ
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/topcharlestonagents/?hl=en
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Charleston Real Estate Podcast with Michael Smith'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Charleston Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Top Charleston Agents Real Estate Team - your professional Charleston Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Charleston, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Michael Smith'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Charleston Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#660032'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#660032'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
